site_name: Modu documentation
site_url: https://example.com/
nav:
  - Home: 'index.md'
  - Introduction: 'introduction.md'
  - Architecture: 'architecture.md'
  - Implementation: 
    - Metrics: 'metric.md'
    - Aggregations: 'aggregation.md'

theme: readthedocs