name: Run [METRICs] Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and0test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.2.2"
      - run: mkdir -p grammars build
      - run: cd grammars && git clone https://github.com/tree-sitter/tree-sitter-python && cd -
      - run: poetry install
      - run: poetry run python byoqm/build_treesitter.py
      - run: cd metrics/test
      - run: poetry run python -m unittest
