name: "coverage"
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  unit_tests:
    name: Unit test regression
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          architecture: "x64"
          token: ${{ github.token }}
      - run: pip install -r requirements.txt
      - run: python -m unittest discover
  code_coverage:
    name: Unit test coverage
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          architecture: "x64"
          token: ${{ github.token }}
      - run: pip install -r requirements.txt
      - run: coverage run --source=byoqm/ -m unittest discover
      - run: coverage xml
      - uses: orgoro/coverage@v3
        with:
          coverageFile: ./coverage.xml
          token: ${{ github.token }}
          thresholdAll: 0.8
          thresholdNew: 0.8
