name: "coverage"
on:
  pull_request:
    branches:
      - master
      - main
test:
  coverage:
    runs-on: ubuntu-latest
    steps:
        - uses: orgoro/coverage@v3
        - uses: ./
        with:
          coverageFile: coverage.xml
          thresholdNew: 0.8
          thresholdModified: 0.0
          token: ${{ secrets.GITHUB_TOKEN }}
