name: "Code Coverage"
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Get Cover
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
