name: Test coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.11.1
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.1"
      - name: Curling poetry
      - run: curl -sSL https://install.python-poetry.org | python3
      - name: Installing poetry
      - run: poetry install
      - name: Installing coverage.
      - run: poetry add coverage==7.1.0
      - name: Running unit tests
        run: coverage run -m unittest
      - name: Test coverage
        run: coverage report --fail-under=0
